rpg-demo.front-end.url: "http://localhost:5173"
rpg-demo.deploy.url: "http://localhost:5173"

spring:
  profiles:
    active: dev,debug
  datasource:
    url: jdbc:h2:file:./data/rpgdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
