spring:
  datasource:
    url: jdbc:h2:file:./data/rpgdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update   # o validate / create-drop, a seconda dei tuoi casi
    show-sql: true
    properties:
      hibernate:
        format_sql: true
